name: test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['14', '16', '18']
    name: ${{ matrix.os }} Use Node.js ${{ matrix.node }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.11.0
          run_install: true
      - name: Jest
        run: pnpm test
